apiVersion: v1
kind: Service
metadata:
  name: bank-collection-name
  labels:
    app: bank-collection-name
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bank-collection-name
