server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pesco_db
    username: postgres
    password: 'powergrid@2?.net'
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 20000
      pool-name: HikariPool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
jwt:
  secret-key: lcBCilFEQT0SWEZcCQhGx2UaCZcxPx4bYBfrGM0DVKDJycK2UL4dDJqAkZ8r4IBQxSa3S2wlTVlnVVzvzP5sfzPtLUournmEY2N3ZGVnQ1BtWEF0anZ0aDNLNHJhaHh9IkFVaj0PXA==

auth-service:
  base-url: http://localhost:8080

notification-service:
  base-url: http://localhost:8070

logging:
  level:
    org.springframework.security: DEBUG

cache:
  type: redis
redis:
  host: localhost
  port: 6379
