apiVersion: v1
kind: Service
metadata:
  name: authentication-name
  labels:
    app: authentication-name
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: authentication-name
