apiVersion: apps/v1
kind: Deployment
metadata:
  name: beneficiary-service
  labels:
    app: beneficiary-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beneficiary-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: beneficiary-service
    spec:
      containers:
      - name: beneficiary-service
        image: davidakpele/bank_beneficiary_service:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENV_VARIABLE_NAME
          value: "value"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: beneficiary-service
spec:
  selector:
    app: beneficiary-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: beneficiary-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: beneficiary-service-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80